repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-added-large-files
      args: ['--maxkb=500']  # block >500KB accidentally added

- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.2
  hooks:
    - id: gitleaks

# ----------------------------
# #2: local symlink check hook
# ----------------------------
- repo: local
  hooks:
    - id: symlink-check
      name: symlink-check
      entry: bash scripts/check_symlinks.sh
      language: system
      pass_filenames: false

# Ignore gigantic CSVs for whitespace-only hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: end-of-file-fixer
      exclude: ^play_by_play_(2022|2024)\.csv$
    - id: trailing-whitespace
      exclude: ^play_by_play_(2022|2024)\.csv$
