name: calibration-check

on:
  push:
  pull_request:

jobs:
  cal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install CLI tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scipy scikit-learn csvkit

      - name: Fit calibrator on pinned history (no network)
        env:
          CAL_TRAIN_HISTORY_GLOB: "history/enriched_202[2-4]*.csv"
          CAL_TRAIN_START_SEASON: "2022"
          CAL_TRAIN_END_SEASON: "2024"
          MIN_CAL_ROWS: "200"
        run: |
          python3 scripts/refit_model_line_calibration.py
          jq . out/calibration/model_line_calibration.json
          jq . out/calibration/meta.json

      - name: Health checks (non-identity, no coinflips, correct glob)
        run: |
          jq -e '.a!=null and .b!=null and .n==240' out/calibration/model_line_calibration.json
          jq -e '.n_rows==240 and .hist_glob=="history/enriched_202[2-4]*.csv"' out/calibration/meta.json
          csvcut -c p out/calibration/train_sample.csv | tail -n +2 | awk '{if($1==0.5) f=1} END{exit(f)}'
